# Generated by Django 2.2.24 on 2022-05-03 06:36

from django.db import migrations


def new_building_auto_filler(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.new_building = flat.construction_year > 2014
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(new_building_auto_filler),
    ]
