# Generated by Django 2.2.24 on 2022-05-03 08:30

from django.db import migrations

def owners_flats_relation_autocreator(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        related_flats = Flat.objects.filter(owner=owner.owner_name)
        owner.flats_of_owner.set(related_flats)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220503_1111'),
    ]

    operations = [
        migrations.RunPython(owners_flats_relation_autocreator)
    ]
